"""Add unban column

Revision ID: a2f281e3edf1
Revises: 9c6a7ab99aa6
Create Date: 2018-07-27 18:45:22.516721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f281e3edf1'
down_revision = '9c6a7ab99aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unban_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'unban_date')
    # ### end Alembic commands ###
