"""Something

Revision ID: f33ef034810a
Revises: 094eed3a2fa3
Create Date: 2018-07-23 15:05:10.143514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f33ef034810a'
down_revision = '094eed3a2fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
